# Generated by Django 5.1.7 on 2026-05-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('hospitals', '0001_add_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('auth', 'Auth'), ('patient', 'Patient'), ('record', 'Record'), ('staff', 'Staff'), ('emergency', 'Emergency'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20),
        ),
    ]
