# Generated by Django 5.1.7 on 2026-05-08 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Zimbabwe national ID (e.g. 63-2400679R42).', regex='^\\d{2}-\\d{7}[A-Za-z]\\d{2}$')]),
        ),
    ]
