# Generated by Django 5.1.7 on 2026-05-08 23:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_add_hospital'),
        ('patients', '0002_zim_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Zimbabwe national ID (e.g. 63-2400679R42).', regex='^\\d{2}-\\d{7}[A-Z]\\d{2}$')]),
        ),
    ]
