# Generated by Django 5.1.7 on 2026-05-14 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_chronic_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be in format DD-NNNNNNNLCC (e.g. 63-2400679R42).', regex='^\\d{2}-\\d{7}[A-Za-z]\\d{2}$')]),
        ),
    ]
