# Generated by Django 5.1.7 on 2026-05-14 12:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_facility_type_other'),
        ('patients', '0005_alter_patient_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='existing_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_surgeries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_type',
            field=models.CharField(choices=[('newborn', 'Newborn'), ('existing', 'Existing Person')], default='existing', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be in format DD-NNNNNNNLCC (e.g. 63-2400679R42).', regex='^\\d{2}-\\d{7}[A-Za-z]\\d{2}$')]),
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('birth', 'Birth Record'), ('consultation', 'Consultation'), ('diagnosis', 'Diagnosis'), ('medication', 'Medication'), ('emergency', 'Emergency'), ('sensitive', 'Sensitive Clinical Record')], max_length=20)),
                ('event_date', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('sensitive_category', models.CharField(blank=True, choices=[('hiv', 'HIV/AIDS'), ('reproductive', 'Reproductive Health'), ('mental_health', 'Mental Health'), ('substance', 'Substance Use'), ('other', 'Other Sensitive')], max_length=20)),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('normal', 'Normal Vaginal Delivery'), ('cesarean', 'Cesarean Section'), ('assisted', 'Assisted Delivery')], max_length=20)),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_complications', models.TextField(blank=True)),
                ('apgar_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('initial_observations', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_events', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='patients.patient')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
